name: "Tugboat Test Repository Seeder"
description: "Tugboat checks out your GitHub repository, and seeds it with new/changed workflows and actions, for functionality tests and demonstration purposes"

inputs:
  target-repo:
    description: "GitHub repository to test (e.g., {owner}/{repo})"
    required: true
  fetch-depth:
    description: "Number of commits to fetch. 0 fetches all history"
    required: false
    default: "1"
  fetch-tags:
    description: "Whether to fetch all tags"
    required: false
    default: "false"
  github-assets:
    description: "List of .github assets to copy (path-qualified from .github/)"
    required: false
  github-token:
    description: "GitHub token for authentication"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Checkout test target repository
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.target-repo }}
        token: ${{ inputs.github-token }}
        fetch-depth: ${{ inputs.fetch-depth }}
        fetch-tags: ${{ inputs.fetch-tags }}

    - name: Checkout dugout repository
      uses: actions/checkout@v4
      with:
        path: dugout
        clean: false

    - name: Copy test target repository's GitHub assets
      if: inputs.github-assets
      shell: bash
      run: |
        # Process JSON array of assets
        echo '${{ inputs.github-assets }}' | jq -r '.[]' | while read -r asset; do
          if [ ! -z "$asset" ]; then
            # Create directory if it doesn't exist
            mkdir -p "${{ github.workspace }}/.github/$(dirname $asset)"
            # Copy the file
            cp -f "${{ github.workspace }}/dugout/.github/$asset" "${{ github.workspace }}/.github/$asset"
            echo "Checking if asset was copied successfully..."
            ls -lh "${{ github.workspace }}/.github/$asset"
          fi
        done
